# Стенд: MySQL 8 + phpMyAdmin + веб-интерфейс поиска (PHP)
services:
  db:
    image: mysql:8.0
    container_name: books_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: library
      MYSQL_PASSWORD: library
    ports:
      - "3307:3306"
    volumes:
      # при первом запуске выполняются по алфавиту
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./sql/04_procedures.sql:/docker-entrypoint-initdb.d/04_procedures.sql:ro
      - ./sql:/sql:ro

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: books_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    build: ./web
    container_name: books_web
    environment:
      DB_HOST: db
      DB_NAME: library
      DB_USER: library
      DB_PASS: library
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
